"""Initial migration.

Revision ID: c94de6587242
Revises: 
Create Date: 2025-08-26 22:59:15.658484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94de6587242'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('brand4')
    op.drop_table('brand3')
    op.drop_table('model3')
    op.drop_table('model4')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model4',
    sa.Column('modelid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brandid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brandid'], ['brand4.brandid'], name='model4_brandid_fkey'),
    sa.PrimaryKeyConstraint('modelid', name='model4_pkey')
    )
    op.create_table('model3',
    sa.Column('modelid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('brandid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brandid'], ['brand3.brandid'], name='model3_brandid_fkey'),
    sa.PrimaryKeyConstraint('modelid', name='model3_pkey')
    )
    op.create_table('brand3',
    sa.Column('brandid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('brandid', name='brand3_pkey')
    )
    op.create_table('brand4',
    sa.Column('brandid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('brandid', name='brand4_pkey')
    )
    # ### end Alembic commands ###
